using System.Linq.Expressions;
using Zeta.Adapters;
using Zeta.Conditional;
using Zeta.Core;
using Zeta.Rules;
using Zeta.Validators;

namespace Zeta.Schemas;

/// <summary>
/// A context-aware schema for validating object values.
/// </summary>
public partial class ObjectContextSchema<T, TContext> : ContextSchema<T, TContext, ObjectContextSchema<T, TContext>> where T : class
{
    private readonly List<IFieldContextValidator<T, TContext>> _fields;
    private readonly List<IConditionalBranch<T, TContext>> _conditionals;

    internal ObjectContextSchema() : this(new ContextRuleEngine<T, TContext>(), [], [])
    {
    }

    internal ObjectContextSchema(ContextRuleEngine<T, TContext> rules, List<IFieldContextValidator<T, TContext>> fields, List<IConditionalBranch<T, TContext>> conditionals) : base(rules)
    {
        _fields = fields;
        _conditionals = conditionals;
    }

    internal ObjectContextSchema(
        ContextlessRuleEngine<T> rules,
        IReadOnlyList<IFieldContextlessValidator<T>> fields,
        IReadOnlyList<IContextlessConditionalBranch<T>> conditionals) : base(rules.ToContext<TContext>())
    {
        _fields = fields.Select(f => (IFieldContextValidator<T, TContext>)new FieldContextlessValidatorAdapter<T, TContext>(f)).ToList();
        _conditionals = conditionals.Select(c => (IConditionalBranch<T, TContext>)new ContextlessConditionalBranchAdapter<T, TContext>(c)).ToList();
    }

    public override async ValueTask<Result> ValidateAsync(T? value, ValidationContext<TContext> context)
    {
        if (value is null)
        {
            return AllowNull
                ? Result.Success()
                : Result.Failure([new ValidationError(context.Path, "null_value", "Value cannot be null")]);
        }

        List<ValidationError>? errors = null;

        var ruleErrors = await Rules.ExecuteAsync(value, context);
        if (ruleErrors != null)
        {
            errors ??= [];
            errors.AddRange(ruleErrors);
        }

        foreach (var field in _fields)
        {
            var fieldErrors = await field.ValidateAsync(value, context);
            if (fieldErrors.Count <= 0) continue;
            errors ??= [];
            errors.AddRange(fieldErrors);
        }

        foreach (var conditional in _conditionals)
        {
            var conditionalErrors = await conditional.ValidateAsync(value, context);
            if (conditionalErrors.Count <= 0) continue;
            errors ??= [];
            errors.AddRange(conditionalErrors);
        }

        return errors == null
            ? Result.Success()
            : Result.Failure(errors);
    }

    public ObjectContextSchema<T, TContext> Field<TProperty>(
        Expression<Func<T, TProperty?>> propertySelector,
        ISchema<TProperty, TContext> schema)
    {
        var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
        var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
        
        // This validates nullable property TProperty? using schema for TProperty.
        var wrapper = NullableAdapterFactory.CreateContextWrapper(schema);
        
        _fields.Add(new FieldContextContextValidator<T, TProperty?, TContext>(propertyName, getter, wrapper));
        return this;
    }

    // Field overloads for primitive types with fluent builders are generated by SchemaFactoryGenerator

    // public ObjectContextSchema<T, TContext> When(
    //     Func<T, bool> condition,
    //     Action<ConditionalBuilder<T, TContext>> thenBranch,
    //     Action<ConditionalBuilder<T, TContext>>? elseBranch = null)
    // {
    //     var thenBuilder = new ConditionalBuilder<T, TContext>();
    //     thenBranch(thenBuilder);
    //
    //     ConditionalBuilder<T, TContext>? elseBuilder = null;
    //     if (elseBranch != null)
    //     {
    //         elseBuilder = new ConditionalBuilder<T, TContext>();
    //         elseBranch(elseBuilder);
    //     }
    //
    //     _conditionals.Add(new ConditionalBranch<T, TContext>(condition, thenBuilder, elseBuilder));
    //     return this;
    // }

    // public ObjectContextSchema<T, TContext> When(
    //     Func<T, TContext, bool> condition,
    //     Action<ConditionalBuilder<T, TContext>> thenBranch,
    //     Action<ConditionalBuilder<T, TContext>>? elseBranch = null)
    // {
    //     var thenBuilder = new ConditionalBuilder<T, TContext>();
    //     thenBranch(thenBuilder);
    //
    //     ConditionalBuilder<T, TContext>? elseBuilder = null;
    //     if (elseBranch != null)
    //     {
    //         elseBuilder = new ConditionalBuilder<T, TContext>();
    //         elseBranch(elseBuilder);
    //     }
    //
    //     _conditionals.Add(new ContextAwareConditionalBranch<T, TContext>(condition, thenBuilder, elseBuilder));
    //     return this;
    // }
}