using System.Text;

namespace Zeta.SourceGenerators;

/// <summary>
/// Generates extension methods for DictionarySchema .EachKey() and .EachValue() operations.
/// </summary>
internal static class DictionaryExtensionsGenerator
{
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Zeta.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace Zeta.Schemas;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for type-specific dictionary schema transformations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class DictionarySchemaExtensions");
        sb.AppendLine("{");

        GenerateContextlessKeyExtensions(sb);
        GenerateContextlessValueExtensions(sb);
        GenerateContextAwareKeyExtensions(sb);
        GenerateContextAwareValueExtensions(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateContextlessKeyExtensions(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Applies transformations to the {{mapping.Type}} key schema for each key in the dictionary.
                                /// </summary>
                                public static DictionaryContextlessSchema<{{mapping.Type}}, TValue> EachKey<TValue>(
                                    this DictionaryContextlessSchema<{{mapping.Type}}, TValue> schema,
                                    Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}>> keyTransform)
                                {
                                    var newKeySchema = keyTransform({{mapping.FactoryMethod}}());
                                    return schema.WithKeySchema(newKeySchema);
                                }

                            """);
        }

        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Applies transformations to the {{mapping.Type}} key schema for each key in the dictionary.
                            /// </summary>
                            public static DictionaryContextlessSchema<{{mapping.Type}}, TValue> EachKey<TValue>(
                                this DictionaryContextlessSchema<{{mapping.Type}}, TValue> schema,
                                Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}>> keyTransform)
                            {
                                var newKeySchema = keyTransform({{mapping.FactoryMethod}}());
                                return schema.WithKeySchema(newKeySchema);
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateContextlessValueExtensions(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Applies transformations to the {{mapping.Type}} value schema for each value in the dictionary.
                                /// </summary>
                                public static DictionaryContextlessSchema<TKey, {{mapping.Type}}> EachValue<TKey>(
                                    this DictionaryContextlessSchema<TKey, {{mapping.Type}}> schema,
                                    Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}>> valueTransform)
                                    where TKey : notnull
                                {
                                    var newValueSchema = valueTransform({{mapping.FactoryMethod}}());
                                    return schema.WithValueSchema(newValueSchema);
                                }

                            """);
        }

        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Applies transformations to the {{mapping.Type}} value schema for each value in the dictionary.
                            /// </summary>
                            public static DictionaryContextlessSchema<TKey, {{mapping.Type}}> EachValue<TKey>(
                                this DictionaryContextlessSchema<TKey, {{mapping.Type}}> schema,
                                Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}>> valueTransform)
                                where TKey : notnull
                            {
                                var newValueSchema = valueTransform({{mapping.FactoryMethod}}());
                                return schema.WithValueSchema(newValueSchema);
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateContextAwareKeyExtensions(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Applies transformations to the {{mapping.Type}} key schema for each key in the dictionary.
                                /// </summary>
                                public static DictionaryContextSchema<{{mapping.Type}}, TValue, TContext> EachKey<TValue, TContext>(
                                    this DictionaryContextSchema<{{mapping.Type}}, TValue, TContext> schema,
                                    Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}, TContext>> keyTransform)
                                {
                                    var newKeySchema = keyTransform({{mapping.FactoryMethod}}());
                                    return schema.WithKeySchema(newKeySchema);
                                }

                            """);
        }

        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Applies transformations to the {{mapping.Type}} key schema for each key in the dictionary.
                            /// </summary>
                            public static DictionaryContextSchema<{{mapping.Type}}, TValue, TContext> EachKey<TValue, TContext>(
                                this DictionaryContextSchema<{{mapping.Type}}, TValue, TContext> schema,
                                Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}, TContext>> keyTransform)
                            {
                                var newKeySchema = keyTransform({{mapping.FactoryMethod}}());
                                return schema.WithKeySchema(newKeySchema);
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateContextAwareValueExtensions(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Applies transformations to the {{mapping.Type}} value schema for each value in the dictionary.
                                /// </summary>
                                public static DictionaryContextSchema<TKey, {{mapping.Type}}, TContext> EachValue<TKey, TContext>(
                                    this DictionaryContextSchema<TKey, {{mapping.Type}}, TContext> schema,
                                    Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}, TContext>> valueTransform)
                                    where TKey : notnull
                                {
                                    var newValueSchema = valueTransform({{mapping.FactoryMethod}}());
                                    return schema.WithValueSchema(newValueSchema);
                                }

                            """);
        }

        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Applies transformations to the {{mapping.Type}} value schema for each value in the dictionary.
                            /// </summary>
                            public static DictionaryContextSchema<TKey, {{mapping.Type}}, TContext> EachValue<TKey, TContext>(
                                this DictionaryContextSchema<TKey, {{mapping.Type}}, TContext> schema,
                                Func<{{mapping.SchemaClass}}, ISchema<{{mapping.Type}}, TContext>> valueTransform)
                                where TKey : notnull
                            {
                                var newValueSchema = valueTransform({{mapping.FactoryMethod}}());
                                return schema.WithValueSchema(newValueSchema);
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }
}
