using System.Linq;
using System.Text;

namespace Zeta.SourceGenerators;

/// <summary>
/// Generates Field overload methods for ObjectContextSchema (context-aware).
/// </summary>
internal static class ObjectContextSchemaFieldGenerator
{
    private const string PropertyPreamble = """
                            var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                            var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
            """;

    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Zeta.Core;");
        sb.AppendLine("using Zeta.Validators;");
        sb.AppendLine();
        sb.AppendLine("namespace Zeta.Schemas;");
        sb.AppendLine();
        sb.AppendLine("public partial class ObjectContextSchema<T, TContext>");
        sb.AppendLine("{");

        GenerateMappingGroup(sb, SchemaMapping.PrimitiveMappings, conditional: false);
        GenerateMappingGroup(sb, SchemaMapping.ModernNetMappings, conditional: true);
        GenerateNestedObjectOverloads(sb);
        GenerateCollectionOverloads(sb);
        GenerateGenericCollectionOverloads(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateMappingGroup(StringBuilder sb, SchemaMapping.Mapping[] mappings, bool conditional)
    {
        if (conditional) sb.AppendLine("#if !NETSTANDARD2_0");
        GenerateInlineBuilderOverloads(sb, mappings);
        GenerateNonNullablePrebuiltContextlessOverloads(sb, mappings);
        GenerateNonNullablePrebuiltContextAwareOverloads(sb, mappings);
        GenerateNullableInlineBuilderOverloads(sb, mappings);
        GenerateNullablePrebuiltContextlessOverloads(sb, mappings);
        GenerateNullablePrebuiltContextAwareOverloads(sb, mappings);
        if (conditional) sb.AppendLine("#endif");
    }

    private static void GenerateInlineBuilderOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings)
        {
            var selectorType = mapping.IsValueType ? mapping.Type : $"{mapping.Type}?";
            var getterExpr = mapping.IsValueType ? "getter" : "instance => getter(instance)!";

            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{selectorType}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.ContextSchemaClass}}<TContext>> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, {{getterExpr}}, schema({{mapping.FactoryMethod}}())));
                                }

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{selectorType}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                {{PropertyPreamble}}
                                    var configuredSchema = schema({{mapping.FactoryMethod}}());
                                    return AddField(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, {{getterExpr}}, configuredSchema.Using<TContext>()));
                                }

                            """);
        }
    }

    private static void GenerateNonNullablePrebuiltContextlessOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built contextless schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddContextlessField(new FieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema));
                                }

                            """);
        }
    }

    private static void GenerateNonNullablePrebuiltContextAwareOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built context-aware schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    ISchema<{{mapping.Type}}, TContext> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                }

                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built Zeta context-aware schema.
                                /// This overload avoids ambiguity when the schema is also assignable to ISchema&lt;{{mapping.Type}}&gt;.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    IContextSchema<{{mapping.Type}}, TContext> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, (ISchema<{{mapping.Type}}, TContext>)schema));
                                }

                            """);
        }
    }

    private static void GenerateNullableInlineBuilderOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with contextless fluent schema builder.
                                /// Null values skip validation. Non-null values are validated by the configured schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddContextlessField(new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema({{mapping.FactoryMethod}}())));
                                }

                            """);
        }
    }

    private static void GenerateNullablePrebuiltContextlessOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built contextless schema.
                                /// Null values skip validation. Non-null values are validated by the provided schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddContextlessField(new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema));
                                }

                            """);
        }
    }

    private static void GenerateNullablePrebuiltContextAwareOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built context-aware schema.
                                /// Null values skip validation. Non-null values are validated by the provided schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}, TContext> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new NullableFieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                }

                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built Zeta context-aware schema.
                                /// This overload avoids ambiguity when the schema is also assignable to ISchema&lt;{{mapping.Type}}&gt;.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    IContextSchema<{{mapping.Type}}, TContext> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new NullableFieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, (ISchema<{{mapping.Type}}, TContext>)schema));
                                }

                            """);
        }
    }

    private static void GenerateNestedObjectOverloads(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties.
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextSchema<TProperty, TContext>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              return AddField(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, schema(Z.Object<TProperty>())));
                          }

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties (contextless builder).
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextlessSchema<TProperty>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var configuredSchema = schema(Z.Object<TProperty>());
                              return AddField(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, configuredSchema.Using<TContext>()));
                          }
                      """);
    }

    private static void GenerateCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            foreach (var mapping in SchemaMapping.PrimitiveMappings)
            {
                var collectionType = string.Format(collectionPattern, mapping.Type);
                var collectionTypeXml = collectionType.Replace("<", "&lt;").Replace(">", "&gt;");

                sb.AppendLine($$"""

                                    /// <summary>
                                    /// Adds a field validator with fluent schema builder for {{collectionTypeXml}} properties.
                                    /// </summary>
                                    public ObjectContextSchema<T, TContext> Field(
                                        Expression<Func<T, {{collectionType}}>> propertySelector,
                                        Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextSchema<{{mapping.Type}}, TContext>> schema)
                                    {
                                        var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                        var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                        var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                        return AddField(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, schema(collectionSchema)));
                                    }

                                    /// <summary>
                                    /// Adds a field validator with fluent schema builder for {{collectionTypeXml}} properties (contextless builder).
                                    /// </summary>
                                    public ObjectContextSchema<T, TContext> Field(
                                        Expression<Func<T, {{collectionType}}>> propertySelector,
                                        Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextlessSchema<{{mapping.Type}}>> schema)
                                    {
                                        var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                        var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                        var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                        var configuredSchema = schema(collectionSchema);
                                        return AddField(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, configuredSchema.Using<TContext>()));
                                    }
                                """);
            }
        }
    }

    private static void GenerateGenericCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            var collectionType = string.Format(collectionPattern, "TElement");

            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{collectionType}} properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field<TElement>(
                                    Expression<Func<T, {{collectionType}}>> propertySelector,
                                    Func<CollectionContextlessSchema<TElement>, CollectionContextSchema<TElement, TContext>> schema)
                                    where TElement : class
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<TElement>();
                                    return AddField(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, schema(collectionSchema)));
                                }

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{collectionType}} properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field<TElement>(
                                    Expression<Func<T, {{collectionType}}>> propertySelector,
                                    Func<CollectionContextlessSchema<TElement>, CollectionContextlessSchema<TElement>> schema)
                                    where TElement : class
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<TElement>();
                                    var configuredSchema = schema(collectionSchema);
                                    return AddField(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, configuredSchema.Using<TContext>()));
                                }
                            """);
        }
    }
}
