using System.Linq;
using System.Text;

namespace Zeta.SourceGenerators;

/// <summary>
/// Generates Field overload methods for ObjectContextSchema (context-aware).
/// </summary>
internal static class ObjectContextSchemaFieldGenerator
{
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Zeta.Core;");
        sb.AppendLine("using Zeta.Validators;");
        sb.AppendLine();
        sb.AppendLine("namespace Zeta.Schemas;");
        sb.AppendLine();
        sb.AppendLine("public partial class ObjectContextSchema<T, TContext>");
        sb.AppendLine("{");

        GeneratePrimitiveFieldOverloads(sb);
        GenerateNullableValueTypeContextlessBuilderOverloads(sb);
        GenerateNullableValueTypeContextAwareBuilderOverloads(sb);
        GenerateNullableValueTypePrebuiltContextlessSchemaOverloads(sb);
        GenerateNullableValueTypePrebuiltContextAwareSchemaOverloads(sb);
        GenerateDateOnlyTimeOnlyOverloads(sb);
        GenerateNullableModernNetContextlessBuilderOverloads(sb);
        GenerateNullableModernNetContextAwareBuilderOverloads(sb);
        GenerateNullableModernNetPrebuiltContextlessSchemaOverloads(sb);
        GenerateNullableModernNetPrebuiltContextAwareSchemaOverloads(sb);
        GenerateNestedObjectOverload(sb);
        GenerateListCollectionOverloads(sb);
        GenerateArrayCollectionOverloads(sb);
        GenerateGenericArrayOverload(sb);
        GenerateGenericListOverload(sb);
        GenerateGenericListContextlessOverload(sb);
        GenerateGenericArrayContextlessOverload(sb);
        GeneratePrimitiveArrayContextlessOverloads(sb);
        GeneratePrimitiveListContextlessOverloads(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GeneratePrimitiveFieldOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, ContextSchema<{{mapping.Type}}, TContext>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema({{mapping.FactoryMethod}}())));
                                    return this;
                                }

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var configuredSchema = schema({{mapping.FactoryMethod}}());
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypeContextlessBuilderOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with contextless fluent schema builder.
                                /// The non-nullable schema is automatically wrapped with .Nullable() and promoted to context-aware.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var configuredSchema = schema({{mapping.FactoryMethod}}());
                                    var nullableSchema = configuredSchema.Nullable();
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema.WithContext<TContext>()));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypeContextAwareBuilderOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with context-aware fluent schema builder.
                                /// The non-nullable schema is automatically wrapped with NullableValueContextSchema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, ContextSchema<{{mapping.Type}}, TContext>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var configuredSchema = schema({{mapping.FactoryMethod}}());
                                    var nullableSchema = new NullableValueContextSchema<{{mapping.Type}}, TContext>(configuredSchema);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypePrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built contextless schema.
                                /// The non-nullable schema is automatically wrapped with .Nullable() and promoted to context-aware.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var nullableSchema = new NullableValueContextlessSchema<{{mapping.Type}}>(schema);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema.WithContext<TContext>()));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypePrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built context-aware schema.
                                /// The non-nullable schema is automatically wrapped with .Nullable().
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}, TContext> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var nullableSchema = new NullableValueContextSchema<{{mapping.Type}}, TContext>(schema);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateDateOnlyTimeOnlyOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                Func<{{mapping.SchemaClass}}, ContextSchema<{{mapping.Type}}, TContext>> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema({{mapping.FactoryMethod}}())));
                                return this;
                            }

                            /// <summary>
                            /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties (contextless builder).
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var configuredSchema = schema({{mapping.FactoryMethod}}());
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetContextlessBuilderOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with contextless fluent schema builder.
                            /// The non-nullable schema is automatically wrapped with .Nullable() and promoted to context-aware.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var configuredSchema = schema({{mapping.FactoryMethod}}());
                                var nullableSchema = configuredSchema.Nullable();
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema.WithContext<TContext>()));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetContextAwareBuilderOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with context-aware fluent schema builder.
                            /// The non-nullable schema is automatically wrapped with NullableValueContextSchema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                Func<{{mapping.SchemaClass}}, ContextSchema<{{mapping.Type}}, TContext>> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var configuredSchema = schema({{mapping.FactoryMethod}}());
                                var nullableSchema = new NullableValueContextSchema<{{mapping.Type}}, TContext>(configuredSchema);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetPrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built contextless schema.
                            /// The non-nullable schema is automatically wrapped with .Nullable() and promoted to context-aware.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                ISchema<{{mapping.Type}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var nullableSchema = new NullableValueContextlessSchema<{{mapping.Type}}>(schema);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema.WithContext<TContext>()));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetPrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built context-aware schema.
                            /// The non-nullable schema is automatically wrapped with .Nullable().
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                ISchema<{{mapping.Type}}, TContext> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var nullableSchema = new NullableValueContextSchema<{{mapping.Type}}, TContext>(schema);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}?, TContext>(propertyName, getter, nullableSchema));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNestedObjectOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties.
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextSchema<TProperty, TContext>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              _fields.Add(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, schema(Z.Object<TProperty>())));
                              return this;
                          }

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties (contextless builder).
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextlessSchema<TProperty>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var configuredSchema = schema(Z.Object<TProperty>());
                              _fields.Add(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                              return this;
                          }
                      """);
    }

    private static void GenerateListCollectionOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            var typeForXml = mapping.Type.Replace("<", "&lt;").Replace(">", "&gt;");
            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for List&lt;{{typeForXml}}&gt; properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, System.Collections.Generic.List<{{mapping.Type}}>>> propertySelector,
                                    Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextSchema<{{mapping.Type}}, TContext>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, schema(collectionSchema)));
                                    return this;
                                }
                            """);
        }
    }

    private static void GenerateArrayCollectionOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            var typeForXml = mapping.Type.Replace("<", "&lt;").Replace(">", "&gt;");
            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{typeForXml}}[] properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}[]>> propertySelector,
                                    Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextSchema<{{mapping.Type}}, TContext>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, schema(collectionSchema)));
                                    return this;
                                }
                            """);
        }
    }

    private static void GenerateGenericArrayOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for TElement[] array properties.
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TElement>(
                              Expression<Func<T, TElement[]>> propertySelector,
                              Func<CollectionContextlessSchema<TElement>, CollectionContextSchema<TElement, TContext>> schema)
                              where TElement : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var collectionSchema = Z.Collection<TElement>();
                              _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, schema(collectionSchema)));
                              return this;
                          }
                      """);
    }

    private static void GenerateGenericListOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for List<TElement> properties.
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TElement>(
                              Expression<Func<T, System.Collections.Generic.List<TElement>>> propertySelector,
                              Func<CollectionContextlessSchema<TElement>, CollectionContextSchema<TElement, TContext>> schema)
                              where TElement : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var collectionSchema = Z.Collection<TElement>();
                              _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, schema(collectionSchema)));
                              return this;
                          }
                      """);
    }



    private static void GenerateGenericListContextlessOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for List<TElement> properties (contextless builder).
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TElement>(
                              Expression<Func<T, System.Collections.Generic.List<TElement>>> propertySelector,
                              Func<CollectionContextlessSchema<TElement>, CollectionContextlessSchema<TElement>> schema)
                              where TElement : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var collectionSchema = Z.Collection<TElement>();
                              var configuredSchema = schema(collectionSchema);
                              _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                              return this;
                          }
                      """);
    }


    private static void GenerateGenericArrayContextlessOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for TElement[] properties (contextless builder).
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TElement>(
                              Expression<Func<T, TElement[]>> propertySelector,
                              Func<CollectionContextlessSchema<TElement>, CollectionContextlessSchema<TElement>> schema)
                              where TElement : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var collectionSchema = Z.Collection<TElement>();
                              var configuredSchema = schema(collectionSchema);
                              _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                              return this;
                          }
                      """);
    }

    private static void GeneratePrimitiveArrayContextlessOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            var typeForXml = mapping.Type.Replace("<", "&lt;").Replace(">", "&gt;");
            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{typeForXml}}[] properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}[]>> propertySelector,
                                    Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextlessSchema<{{mapping.Type}}>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                    var configuredSchema = schema(collectionSchema);
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                    return this;
                                }
                            """);
        }
    }

    private static void GeneratePrimitiveListContextlessOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            var typeForXml = mapping.Type.Replace("<", "&lt;").Replace(">", "&gt;");
            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for List&lt;{{typeForXml}}&gt; properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, System.Collections.Generic.List<{{mapping.Type}}>>> propertySelector,
                                    Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextlessSchema<{{mapping.Type}}>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                    var configuredSchema = schema(collectionSchema);
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                    return this;
                                }
                            """);
        }
    }


}
