using System.Linq;
using System.Text;

namespace Zeta.SourceGenerators;

/// <summary>
/// Generates Field overload methods for ObjectContextSchema (context-aware).
/// </summary>
internal static class ObjectContextSchemaFieldGenerator
{
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Zeta.Core;");
        sb.AppendLine("using Zeta.Validators;");
        sb.AppendLine();
        sb.AppendLine("namespace Zeta.Schemas;");
        sb.AppendLine();
        sb.AppendLine("public partial class ObjectContextSchema<T, TContext>");
        sb.AppendLine("{");

        GeneratePrimitiveFieldOverloads(sb);
        GenerateNonNullableValueTypePrebuiltContextlessSchemaOverloads(sb);
        GenerateNonNullableValueTypePrebuiltContextAwareSchemaOverloads(sb);
        GenerateNullableValueTypeContextlessBuilderOverloads(sb);
        GenerateNullableValueTypePrebuiltContextlessSchemaOverloads(sb);
        GenerateNullableValueTypePrebuiltContextAwareSchemaOverloads(sb);
        GenerateDateOnlyTimeOnlyOverloads(sb);
        GenerateNonNullableModernNetPrebuiltContextlessSchemaOverloads(sb);
        GenerateNonNullableModernNetPrebuiltContextAwareSchemaOverloads(sb);
        GenerateNullableModernNetContextlessBuilderOverloads(sb);
        GenerateNullableModernNetPrebuiltContextlessSchemaOverloads(sb);
        GenerateNullableModernNetPrebuiltContextAwareSchemaOverloads(sb);
        GenerateNestedObjectOverload(sb);
        GenerateCollectionOverloads(sb);
        GenerateGenericCollectionOverloads(sb);
        GenerateGenericCollectionContextlessOverloads(sb);
        GenerateCollectionContextlessOverloads(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GeneratePrimitiveFieldOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings)
        {
            var selectorType = mapping.IsValueType ? mapping.Type : $"{mapping.Type}?";
            var getterExpr = mapping.IsValueType ? "getter" : "instance => getter(instance)!";

            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{selectorType}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.ContextSchemaClass}}<TContext>> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, {{getterExpr}}, schema({{mapping.FactoryMethod}}())));
                                    return this;
                                }

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{selectorType}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var configuredSchema = schema({{mapping.FactoryMethod}}());
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, {{getterExpr}}, configuredSchema.WithContext<TContext>()));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNonNullableValueTypePrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built contextless schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(
                                        new FieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema)));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNonNullableValueTypePrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built context-aware schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    ISchema<{{mapping.Type}}, TContext> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypeContextlessBuilderOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with contextless fluent schema builder.
                                /// Null values skip validation. Non-null values are validated by the configured schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var inner = new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema({{mapping.FactoryMethod}}()));
                                    _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(inner));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypePrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built contextless schema.
                                /// Null values skip validation. Non-null values are validated by the provided schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var inner = new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema);
                                    _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(inner));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateNullableValueTypePrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        foreach (var mapping in SchemaMapping.PrimitiveMappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built context-aware schema.
                                /// Null values skip validation. Non-null values are validated by the provided schema.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}, TContext> schema)
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    _fields.Add(new NullableFieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                    return this;
                                }

                            """);
        }
    }

    private static void GenerateDateOnlyTimeOnlyOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                Func<{{mapping.SchemaClass}}, {{mapping.ContextSchemaClass}}<TContext>> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema({{mapping.FactoryMethod}}())));
                                return this;
                            }

                            /// <summary>
                            /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties (contextless builder).
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var configuredSchema = schema({{mapping.FactoryMethod}}());
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNonNullableModernNetPrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built contextless schema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                ISchema<{{mapping.Type}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(
                                    new FieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema)));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNonNullableModernNetPrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built context-aware schema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                ISchema<{{mapping.Type}}, TContext> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                _fields.Add(new FieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetContextlessBuilderOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with contextless fluent schema builder.
                            /// Null values skip validation. Non-null values are validated by the configured schema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var inner = new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema({{mapping.FactoryMethod}}()));
                                _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(inner));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetPrebuiltContextlessSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built contextless schema.
                            /// Null values skip validation. Non-null values are validated by the provided schema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                ISchema<{{mapping.Type}}> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                var inner = new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema);
                                _fields.Add(new FieldContextlessValidatorAdapter<T, TContext>(inner));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNullableModernNetPrebuiltContextAwareSchemaOverloads(StringBuilder sb)
    {
        sb.AppendLine("#if !NETSTANDARD2_0");
        foreach (var mapping in SchemaMapping.ModernNetMappings)
        {
            sb.AppendLine($$"""
                            /// <summary>
                            /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built context-aware schema.
                            /// Null values skip validation. Non-null values are validated by the provided schema.
                            /// </summary>
                            public ObjectContextSchema<T, TContext> Field(
                                Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                ISchema<{{mapping.Type}}, TContext> schema)
                            {
                                var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                _fields.Add(new NullableFieldContextContextValidator<T, {{mapping.Type}}, TContext>(propertyName, getter, schema));
                                return this;
                            }

                        """);
        }
        sb.AppendLine("#endif");
    }

    private static void GenerateNestedObjectOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties.
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextSchema<TProperty, TContext>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              _fields.Add(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, schema(Z.Object<TProperty>())));
                              return this;
                          }

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties (contextless builder).
                          /// </summary>
                          public ObjectContextSchema<T, TContext> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextlessSchema<TProperty>> schema)
                              where TProperty : class
                          {
                              var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                              var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                              var configuredSchema = schema(Z.Object<TProperty>());
                              _fields.Add(new FieldContextContextValidator<T, TProperty, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                              return this;
                          }
                      """);
    }

    private static void GenerateCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            foreach (var mapping in SchemaMapping.PrimitiveMappings)
            {
                var collectionType = string.Format(collectionPattern, mapping.Type);
                var collectionTypeXml = collectionType.Replace("<", "&lt;").Replace(">", "&gt;");

                sb.AppendLine($$"""

                                    /// <summary>
                                    /// Adds a field validator with fluent schema builder for {{collectionTypeXml}} properties.
                                    /// </summary>
                                    public ObjectContextSchema<T, TContext> Field(
                                        Expression<Func<T, {{collectionType}}>> propertySelector,
                                        Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextSchema<{{mapping.Type}}, TContext>> schema)
                                    {
                                        var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                        var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                        var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                        _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, schema(collectionSchema)));
                                        return this;
                                    }
                                """);
            }
        }
    }

    private static void GenerateGenericCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            var collectionType = string.Format(collectionPattern, "TElement");

            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{collectionType}} properties.
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field<TElement>(
                                    Expression<Func<T, {{collectionType}}>> propertySelector,
                                    Func<CollectionContextlessSchema<TElement>, CollectionContextSchema<TElement, TContext>> schema)
                                    where TElement : class
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<TElement>();
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, schema(collectionSchema)));
                                    return this;
                                }
                            """);
        }
    }

    private static void GenerateGenericCollectionContextlessOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            var collectionType = string.Format(collectionPattern, "TElement");

            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{collectionType}} properties (contextless builder).
                                /// </summary>
                                public ObjectContextSchema<T, TContext> Field<TElement>(
                                    Expression<Func<T, {{collectionType}}>> propertySelector,
                                    Func<CollectionContextlessSchema<TElement>, CollectionContextlessSchema<TElement>> schema)
                                    where TElement : class
                                {
                                    var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                    var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<TElement>();
                                    var configuredSchema = schema(collectionSchema);
                                    _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<TElement>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                    return this;
                                }
                            """);
        }
    }

    private static void GenerateCollectionContextlessOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            foreach (var mapping in SchemaMapping.PrimitiveMappings)
            {
                var collectionType = string.Format(collectionPattern, mapping.Type);
                var collectionTypeXml = collectionType.Replace("<", "&lt;").Replace(">", "&gt;");

                sb.AppendLine($$"""

                                    /// <summary>
                                    /// Adds a field validator with fluent schema builder for {{collectionTypeXml}} properties (contextless builder).
                                    /// </summary>
                                    public ObjectContextSchema<T, TContext> Field(
                                        Expression<Func<T, {{collectionType}}>> propertySelector,
                                        Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextlessSchema<{{mapping.Type}}>> schema)
                                    {
                                        var propertyName = ObjectContextlessSchema<T>.GetPropertyName(propertySelector);
                                        var getter = ObjectContextlessSchema<T>.CreateGetter(propertySelector);
                                        var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                        var configuredSchema = schema(collectionSchema);
                                        _fields.Add(new FieldContextContextValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>, TContext>(propertyName, getter, configuredSchema.WithContext<TContext>()));
                                        return this;
                                    }
                                """);
            }
        }
    }
}
