using System.Linq;
using System.Text;

namespace Zeta.SourceGenerators;

/// <summary>
/// Generates Field overload methods for ObjectContextlessSchema.
/// </summary>
internal static class ObjectSchemaFieldGenerator
{
    private const string PropertyPreamble = """
                            var propertyName = GetPropertyName(propertySelector);
                            var getter = CreateGetter(propertySelector);
            """;

    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Zeta.Core;");
        sb.AppendLine("using Zeta.Validators;");
        sb.AppendLine();
        sb.AppendLine("namespace Zeta.Schemas;");
        sb.AppendLine();
        sb.AppendLine("public partial class ObjectContextlessSchema<T>");
        sb.AppendLine("{");

        GenerateMappingGroup(sb, SchemaMapping.PrimitiveMappings, conditional: false);
        GenerateMappingGroup(sb, SchemaMapping.ModernNetMappings, conditional: true);
        GenerateNestedObjectOverload(sb);
        GenerateCollectionOverloads(sb);
        GenerateGenericCollectionOverloads(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateMappingGroup(StringBuilder sb, SchemaMapping.Mapping[] mappings, bool conditional)
    {
        if (conditional) sb.AppendLine("#if !NETSTANDARD2_0");
        GenerateInlineBuilderOverloads(sb, mappings);
        GenerateNonNullablePrebuiltOverloads(sb, mappings);
        GenerateNullableInlineBuilderOverloads(sb, mappings);
        GenerateNullablePrebuiltOverloads(sb, mappings);
        if (conditional) sb.AppendLine("#endif");
    }

    private static void GenerateInlineBuilderOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings)
        {
            var selectorType = mapping.IsValueType ? mapping.Type : $"{mapping.Type}?";
            var getterExpr = mapping.IsValueType ? "getter" : "instance => getter(instance)!";

            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{mapping.Type}} properties.
                                /// </summary>
                                public ObjectContextlessSchema<T> Field(
                                    Expression<Func<T, {{selectorType}}>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new FieldContextlessValidator<T, {{mapping.Type}}>(propertyName, {{getterExpr}}, schema({{mapping.FactoryMethod}}())));
                                }

                            """);
        }
    }

    private static void GenerateNonNullablePrebuiltOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for non-nullable {{mapping.Type}} properties with a pre-built schema.
                                /// </summary>
                                public ObjectContextlessSchema<T> Field(
                                    Expression<Func<T, {{mapping.Type}}>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new FieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema));
                                }

                            """);
        }
    }

    private static void GenerateNullableInlineBuilderOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with fluent schema builder.
                                /// Null values skip validation. Non-null values are validated by the configured schema.
                                /// </summary>
                                public ObjectContextlessSchema<T> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    Func<{{mapping.SchemaClass}}, {{mapping.SchemaClass}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema({{mapping.FactoryMethod}}())));
                                }

                            """);
        }
    }

    private static void GenerateNullablePrebuiltOverloads(StringBuilder sb, SchemaMapping.Mapping[] mappings)
    {
        foreach (var mapping in mappings.Where(m => m.IsValueType))
        {
            sb.AppendLine($$"""
                                /// <summary>
                                /// Adds a field validator for nullable {{mapping.Type}}? properties with a pre-built schema.
                                /// Null values skip validation. Non-null values are validated by the provided schema.
                                /// </summary>
                                public ObjectContextlessSchema<T> Field(
                                    Expression<Func<T, {{mapping.Type}}?>> propertySelector,
                                    ISchema<{{mapping.Type}}> schema)
                                {
                                {{PropertyPreamble}}
                                    return AddField(new NullableFieldContextlessValidator<T, {{mapping.Type}}>(propertyName, getter, schema));
                                }

                            """);
        }
    }

    private static void GenerateNestedObjectOverload(StringBuilder sb)
    {
        sb.AppendLine("""

                          /// <summary>
                          /// Adds a field validator with fluent schema builder for nested object properties.
                          /// </summary>
                          public ObjectContextlessSchema<T> Field<TProperty>(
                              Expression<Func<T, TProperty>> propertySelector,
                              Func<ObjectContextlessSchema<TProperty>, ObjectContextlessSchema<TProperty>> schema)
                              where TProperty : class
                          {
                              var propertyName = GetPropertyName(propertySelector);
                              var getter = CreateGetter(propertySelector);
                              return AddField(new FieldContextlessValidator<T, TProperty>(propertyName, getter, schema(Z.Object<TProperty>())));
                          }
                      """);
    }

    private static void GenerateCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            foreach (var mapping in SchemaMapping.PrimitiveMappings)
            {
                var collectionType = string.Format(collectionPattern, mapping.Type);
                var collectionTypeXml = collectionType.Replace("<", "&lt;").Replace(">", "&gt;");

                sb.AppendLine($$"""

                                    /// <summary>
                                    /// Adds a field validator with fluent schema builder for {{collectionTypeXml}} properties.
                                    /// </summary>
                                    public ObjectContextlessSchema<T> Field(
                                        Expression<Func<T, {{collectionType}}>> propertySelector,
                                        Func<CollectionContextlessSchema<{{mapping.Type}}>, CollectionContextlessSchema<{{mapping.Type}}>> schema)
                                    {
                                        var propertyName = GetPropertyName(propertySelector);
                                        var getter = CreateGetter(propertySelector);
                                        var collectionSchema = Z.Collection<{{mapping.Type}}>();
                                        return AddField(new FieldContextlessValidator<T, System.Collections.Generic.ICollection<{{mapping.Type}}>>(propertyName, getter, schema(collectionSchema)));
                                    }
                                """);
            }
        }
    }

    private static void GenerateGenericCollectionOverloads(StringBuilder sb)
    {
        foreach (var collectionPattern in SchemaMapping.Collections)
        {
            var collectionType = string.Format(collectionPattern, "TElement");

            sb.AppendLine($$"""

                                /// <summary>
                                /// Adds a field validator with fluent schema builder for {{collectionType}} properties.
                                /// </summary>
                                public ObjectContextlessSchema<T> Field<TElement>(
                                    Expression<Func<T, {{collectionType}}>> propertySelector,
                                    Func<CollectionContextlessSchema<TElement>, CollectionContextlessSchema<TElement>> schema)
                                    where TElement : class
                                {
                                    var propertyName = GetPropertyName(propertySelector);
                                    var getter = CreateGetter(propertySelector);
                                    var collectionSchema = Z.Collection<TElement>();
                                    return AddField(new FieldContextlessValidator<T, System.Collections.Generic.ICollection<TElement>>(propertyName, getter, schema(collectionSchema)));
                                }
                            """);
        }
    }
}
